### ISSUE TITLE
Add device data collection

### ISSUE THREAD

**Issue by gsmendoza** [solidusio/solidus_braintree#115]
## Goal

We want to add device data collection because PayPal recommends that all customer-initiated transactions include device data. Device data increases the accuracy of their available Premium Fraud Management Tools in determining when a transaction is fraudulent. See https://developer.paypal.com/braintree/docs/guides/premium-fraud-management-tools/device-data-collection.

## Background

@SyborgStudios contributed the initial PR. See https://github.com/solidusio/solidus_braintree/pull/103.

## Tasks

* [x] Remove `IS_FRONTEND` since we now have separate `hosted_form.js` files for frontend and backend.
* [x] Always use data collector in frontend HostedForm.
* [x] Check if client and data-collector JS files are being included:
  * [x] `<script src="https://js.braintreegateway.com/web/3.91.0/js/client.min.js"></script>`
  * [x] `<script src="https://js.braintreegateway.com/web/3.91.0/js/data-collector.min.js"></script>`
  * [ ] Test if PayPal checkout is successful.
